In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter
import matplotlib.dates as mdates
import datetime as dt

# The path to our CSV file
file = "Resources/Metro_Nashville___Davidson_County_Traffic_Crashes__2019_.csv"

# Read our CSV data into pandas
df = pd.read_csv(file, parse_dates = ['Date and Time'])
df.head()

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Reporting Officer,Collision Type Code,Collision Type Description,...,Harmful Code Description,Street Address,City,State,ZIP,RPA,Precinct,Latitude,Longitude,Mapped Location
0,20190004211,2019-01-02 15:58:00,2.0,0.0,0.0,NaN,N,256419,11.0,Front to Rear,...,MOTOR VEHICLE IN TRANSPORT,CHARLOTTE AV & SPRUCE ST,NASHVILLE,TN,NaN,5337.0,NORTH,NaN,NaN,NaN
1,20190025356,2019-01-10 15:37:00,3.0,0.0,0.0,NaN,N,256505,11.0,Front to Rear,...,MOTOR VEHICLE IN TRANSPORT,CHARLOTTE AV & SHORTVIEW AV,NASHVILLE,TN,NaN,5339.0,NORTH,NaN,NaN,NaN
2,20190096838,2019-02-05 12:30:00,2.0,0.0,0.0,NaN,N,267831,98.0,OTHER,...,MOTOR VEHICLE IN TRANSPORT,HILLSBORO PKE & SHARONDALE DR,NASHVILLE,TN,NaN,6001.0,WEST,NaN,NaN,NaN
3,20190112437,2019-02-11 09:53:00,3.0,0.0,0.0,NaN,N,591936,11.0,Front to Rear,...,MOTOR VEHICLE IN TRANSPORT,LOMBARDY AV & HILLSBORO PKE,NASHVILLE,TN,NaN,6001.0,WEST,NaN,NaN,NaN
4,20190129966,2019-02-17 11:06:00,2.0,0.0,0.0,NaN,Y,279116,4.0,ANGLE,...,MOTOR VEHICLE IN TRANSPORT,LOMBARDY AV & HILLSBORO PKE,NASHVILLE,TN,NaN,6001.0,WEST,NaN,NaN,NaN

In [30]:
#Get row count for each column
df.count()

Accident Number               284517
Date and Time                 284446
Number of Motor Vehicles      284346
Number of Injuries            284394
Number of Fatalities          284332
Property Damage               125606
Hit and Run                   284479
Reporting Officer             284389
Collision Type Code           284366
Collision Type Description    283841
Weather Code                  284085
Weather Description           284085
Illumination Code             284151
Illumination Description      284126
Harmful Code                  284516
Harmful Code Description      282897
Street Address                284327
City                          277819
State                         281799
ZIP                           274897
RPA                           270262
Precinct                      269411
Latitude                      272145
Longitude                     272139
Mapped Location               272136
dtype: int64

In [31]:
#Drop nan or blank only in date/time column

df = df.dropna(subset=["Date and Time", "Mapped Location"])

df.head()

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Reporting Officer,Collision Type Code,Collision Type Description,...,Harmful Code Description,Street Address,City,State,ZIP,RPA,Precinct,Latitude,Longitude,Mapped Location
12373,20190402257,2019-05-26 12:41:00,2.0,2.0,0.0,NaN,N,769379,4.0,ANGLE,...,MOTOR VEHICLE IN TRANSPORT,HARDING PL & METROPLEX DR,NASHVILLE,TN,37211,8889.0,SOUTH,36.0868,-86.6959,"(36.0868, -86.6959)"
12374,20190397714,2019-05-24 13:15:00,2.0,0.0,0.0,NaN,Y,299238,5.0,SIDESWIPE - SAME DIRECTION,...,MOTOR VEHICLE IN TRANSPORT,MM 46 7 I 24,NASHVILLE,TN,37207,19060.0,EAST,36.1922,-86.7755,"(36.1922, -86.7755)"
12376,20160338232,2016-04-13 07:35:00,2.0,0.0,0.0,NaN,N,839052,4.0,ANGLE,...,MOTOR VEHICLE IN TRANSPORT,NOLENSVILLE & HICKORYVIEW,NASHVILLE,TN,NaN,NaN,NaN,0.0000,0.0000,"(0.0, 0.0)"
12377,20160838187,2016-09-17 10:20:00,2.0,0.0,0.0,NaN,N,419997,11.0,Front to Rear,...,MOTOR VEHICLE IN TRANSPORT,MM 210 0 I140,NASHVILLE,TN,NaN,NaN,NaN,0.0000,0.0000,"(0.0, 0.0)"
12378,20190413063,2019-05-30 13:23:00,2.0,1.0,0.0,NaN,N,225777,4.0,ANGLE,...,MOTOR VEHICLE IN TRANSPORT,BRILEY PKWY & I40 W EXT RAMP,NASHVILLE,TN,37209,4696.0,WEST,36.1530,-86.8576,"(36.153, -86.8576)"

In [32]:
df['month_year'] = df['Date and Time'].dt.to_period('M')
df['Year'] = pd.DatetimeIndex(df['Date and Time']).year.astype(str)
df['Year'] = df['Year'].astype(str).replace('\.0', '', regex=True)
df['Month'] = pd.DatetimeIndex(df['Date and Time']).month.astype(str)
df['Month'] = df['Month'].astype(str).replace('\.0', '', regex=True)

In [33]:
df.count()

Accident Number               272118
Date and Time                 272118
Number of Motor Vehicles      272032
Number of Injuries            272068
Number of Fatalities          272015
Property Damage               113318
Hit and Run                   272082
Reporting Officer             272060
Collision Type Code           272048
Collision Type Description    271523
Weather Code                  271754
Weather Description           271754
Illumination Code             271823
Illumination Description      271798
Harmful Code                  272117
Harmful Code Description      270498
Street Address                272084
City                          269902
State                         269951
ZIP                           270546
RPA                           269017
Precinct                      268243
Latitude                      272118
Longitude                     272118
Mapped Location               272118
month_year                    272118
Year                          272118
Month                         272118
dtype: int64

In [34]:
#df.astype({"Year" : "int64"})
#df[df.Year == {2010,2011,2012,2013,2014,2015,2016,2017,2018,2019}]
#df.head()
df[(df['Date and Time'].dt.year >= 2010)]

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Reporting Officer,Collision Type Code,Collision Type Description,...,State,ZIP,RPA,Precinct,Latitude,Longitude,Mapped Location,month_year,Year,Month
12373,20190402257,2019-05-26 12:41:00,2.0,2.0,0.0,NaN,N,769379,4.0,ANGLE,...,TN,37211,8889.0,SOUTH,36.0868,-86.6959,"(36.0868, -86.6959)",2019-05,2019,5
12374,20190397714,2019-05-24 13:15:00,2.0,0.0,0.0,NaN,Y,299238,5.0,SIDESWIPE - SAME DIRECTION,...,TN,37207,19060.0,EAST,36.1922,-86.7755,"(36.1922, -86.7755)",2019-05,2019,5
12376,20160338232,2016-04-13 07:35:00,2.0,0.0,0.0,NaN,N,839052,4.0,ANGLE,...,TN,NaN,NaN,NaN,0.0000,0.0000,"(0.0, 0.0)",2016-04,2016,4
12377,20160838187,2016-09-17 10:20:00,2.0,0.0,0.0,NaN,N,419997,11.0,Front to Rear,...,TN,NaN,NaN,NaN,0.0000,0.0000,"(0.0, 0.0)",2016-09,2016,9
12378,20190413063,2019-05-30 13:23:00,2.0,1.0,0.0,NaN,N,225777,4.0,ANGLE,...,TN,37209,4696.0,WEST,36.1530,-86.8576,"(36.153, -86.8576)",2019-05,2019,5
12379,20190415612,2019-05-31 08:45:00,2.0,0.0,0.0,NaN,N,179580,5.0,SIDESWIPE - SAME DIRECTION,...,TN,37208,5415.0,NORTH,36.1707,-86.8013,"(36.1707, -86.8013)",2019-05,2019,5
12380,20190413788,2019-05-30 00:00:00,1.0,0.0,0.0,Y,Y,240955,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,TN,37013,8767.0,SOUTH,35.9955,-86.6879,"(35.9955, -86.6879)",2019-05,2019,5
12381,20190420990,2019-06-02 16:36:00,2.0,0.0,0.0,NaN,N,197054,11.0,Front to Rear,...,TN,37217,8841.0,SOUTH,36.1062,-86.6731,"(36.1062, -86.6731)",2019-06,2019,6
12382,20190420794,2019-06-02 14:45:00,2.0,1.0,0.0,NaN,N,298860,11.0,Front to Rear,...,TN,37076,9613.0,HERMIT,36.1756,-86.6154,"(36.1756, -86.6154)",2019-06,2019,6
12383,20190418647,2019-06-01 13:45:00,1.0,0.0,0.0,Y,N,299265,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,TN,37072,17061.0,MADISO,36.2879,-86.7259,"(36.2879, -86.7259)",2019-06,2019,6
12384,20190418011,2019-06-01 05:15:00,1.0,0.0,0.0,Y,Y,179603,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,TN,37189,3301.0,NORTH,36.2923,-86.8110,"(36.2923, -86.811)",2019-06,2019,6
12385,20190413475,2019-05-30 15:54:00,2.0,0.0,0.0,NaN,N,209184,11.0,Front to Rear,...,TN,37013,8927.0,SOUTH,36.0430,-86.6066,"(36.043, -86.6066)",2019-05,2019,5
12386,20190421063,2019-06-02 17:17:00,2.0,2.0,0.0,NaN,N,197435,4.0,ANGLE,...,TN,37206,1933.0,EAST,36.1933,-86.7519,"(36.1933, -86.7519)",2019-06,2019,6
12387,20190416279,2019-05-31 13:45:00,2.0,0.0,0.0,NaN,N,320588,4.0,ANGLE,...,TN,37208,4343.0,NORTH,36.1806,-86.7963,"(36.1806, -86.7963)",2019-05,2019,5
12388,20190414422,2019-05-30 21:59:00,1.0,0.0,0.0,NaN,Y,161955,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,TN,37207,3003.0,NORTH,36.1962,-86.7767,"(36.1962, -86.7767)",2019-05,2019,5
12389,20190417369,2019-05-31 22:30:00,1.0,0.0,0.0,NaN,N,579971,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,TN,37013,8753.0,SOUTH,36.0449,-86.6704,"(36.0449, -86.6704)",2019-05,2019,5
12390,20190418955,2019-06-01 17:17:00,2.0,0.0,0.0,NaN,N,330444,5.0,SIDESWIPE - SAME DIRECTION,...,TN,37203,5711.0,MIDTOW,36.1496,-86.7980,"(36.1496, -86.798)",2019-06,2019,6
12391,20190420242,2019-06-02 08:15:00,1.0,1.0,0.0,Y,N,320601,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,TN,37135,8773.0,SOUTH,35.9910,-86.6630,"(35.991, -86.663)",2019-06,2019,6
12392,20190414939,2019-05-31 02:00:00,2.0,1.0,0.0,NaN,N,330438,5.0,SIDESWIPE - SAME DIRECTION,...,TN,37210,82061.0,HERMIT,36.1403,-86.7313,"(36.1403, -86.7313)",2019-05,2019,5
12393,20190418609,2019-06-01 13:17:00,2.0,0.0,0.0,NaN,N,311325,5.0,SIDESWIPE - SAME DIRECTION,...,TN,37217,88022.0,HERMIT,36.1434,-86.7031,"(36.1434, -86.7031)",2019-06,2019,6
12394,20190418899,2019-06-01 17:00:00,2.0,0.0,0.0,NaN,N,212330,11.0,Front to Rear,...,TN,37209,4604.0,WEST,36.1830,-86.8662,"(36.183, -86.8662)",2019-06,2019,6
12395,20190417091,2019-05-31 18:15:00,2.0,0.0,0.0,NaN,Y,256412,11.0,Front to Rear,...,TN,37211,8511.0,MIDTOW,36.0933,-86.7362,"(36.0933, -86.7362)",2019-05,2019,5
12396,20190396279,2019-05-23 20:00:00,2.0,0.0,0.0,NaN,Y,660929,9.0,UNKNOWN,...,TN,37207,1995.0,EAST,36.1745,-86.7680,"(36.1745, -86.768)",2019-05,2019,5
12397,20190412799,2019-05-30 10:54:00,3.0,1.0,0.0,NaN,N,352158,11.0,Front to Rear,...,TN,37027,8623.0,MIDTOW,36.0399,-86.7810,"(36.0399, -86.781)",2019-05,2019,5
12398,20190415786,2019-05-31 10:00:00,2.0,0.0,0.0,NaN,Y,493304,4.0,ANGLE,...,TN,37115,1731.0,MADISO,36.2973,-86.6988,"(36.2973, -86.6988)",2019-05,2019,5
12399,20190420890,2019-06-02 15:43:00,2.0,3.0,0.0,NaN,N,298858,2.0,HEAD-ON,...,TN,37213,1007.0,CENTRA,36.1662,-86.7658,"(36.1662, -86.7658)",2019-06,2019,6
12400,20190415927,2019-05-31 07:54:00,2.0,1.0,0.0,NaN,N,571313,11.0,Front to Rear,...,TN,37217,8841.0,SOUTH,36.1129,-86.6890,"(36.1129, -86.689)",2019-05,2019,5
12401,20190416411,2019-05-31 00:00:00,2.0,0.0,0.0,NaN,N,299258,11.0,Front to Rear,...,TN,37115,20044.0,MADISO,36.2481,-86.7430,"(36.2481, -86.743)",2019-05,2019,5
12402,20190416609,2019-05-31 15:09:00,2.0,0.0,0.0,NaN,Y,330444,11.0,Front to Rear,...,TN,37203,6719.0,MIDTOW,36.1516,-86.7885,"(36.1516, -86.7885)",2019-05,2019,5
12403,20190412563,2019-05-18 13:39:00,2.0,0.0,0.0,NaN,Y,156307,11.0,Front to Rear,...,TN,37207,18020.0,EAST,36.2018,-86.7766,"(36.2018, -86.7766)",2019-05,2019,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284483,20201041698,2010-05-10 08:59:00,2.0,1.0,0.0,N,N,224412,4.0,ANGLE,...,TN,37212,6623.0,MIDTOW,36.1375,-86.7994,"(36.1375, -86.7994)",2010-05,2010,5
284484,20201042665,2010-05-14 16:53:00,2.0,0.0,0.0,N,N,224368,1.0,REAR END,...,TN,37115,1729.0,MADISO,36.2758,-86.7099,"(36.2758, -86.7099)",2010-05,2010,5
284485,20201043641,2010-05-17 17:19:00,2.0,0.0,0.0,N,N,716887,1.0,REAR END,...,NaN,37214,NaN,HERMIT,36.1419,-86.6413,"(36.1419, -86.6413)",2010-05,2010,5
284486,20201043950,2010-05-19 05:45:00,1.0,0.0,0.0,N,N,633383,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,NaN,37013,8806.0,SOUTH,36.0146,-86.6204,"(36.0146, -86.6204)",2010-05,2010,5
284487,20201044703,2010-05-19 16:07:00,2.0,1.0,0.0,N,N,687816,4.0,ANGLE,...,TN,37212,5901.0,MIDTOW,36.1317,-86.8014,"(36.1317, -86.8014)",2010-05,2010,5
284488,20201046837,2010-05-28 01:00:00,1.0,0.0,0.0,N,Y,418761,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,TN,37215,6413.0,MIDTOW,36.1087,-86.8068,"(36.1087, -86.8068)",2010-05,2010,5
284491,2020105086,2010-06-11 17:30:00,2.0,0.0,0.0,N,N,714641,1.0,REAR END,...,TN,37210,8101.0,SOUTH,36.1259,-86.7526,"(36.1259, -86.7526)",2010-06,2010,6
284492,20201056036,2010-06-10 18:35:00,3.0,1.0,0.0,N,N,429193,1.0,REAR END,...,NaN,37205,NaN,WEST,36.1258,-86.8465,"(36.1258, -86.8465)",2010-06,2010,6
284493,20201057717,2010-07-06 17:25:00,2.0,0.0,0.0,N,N,665896,1.0,REAR END,...,TN,37076,9561.0,HERMIT,36.1736,-86.6021,"(36.1736, -86.6021)",2010-07,2010,7
284494,20201057986,2010-07-07 15:42:00,2.0,0.0,0.0,N,N,648796,1.0,REAR END,...,TN,37220,8601.0,MIDTOW,36.0811,-86.7584,"(36.0811, -86.7584)",2010-07,2010,7
284495,20201058755,2010-07-10 15:40:00,2.0,0.0,0.0,N,N,646690,1.0,REAR END,...,TN,37215,6103.0,WEST,36.1159,-86.8299,"(36.1159, -86.8299)",2010-07,2010,7
284496,20201063476,2010-07-30 16:03:00,2.0,0.0,0.0,N,Y,562530,3.0,REAR-TO-REAR,...,TN,37076,9613.0,HERMIT,36.1983,-86.6201,"(36.1983, -86.6201)",2010-07,2010,7
284497,20201072119,2010-08-31 06:45:00,2.0,0.0,0.0,N,N,224372,4.0,ANGLE,...,NaN,37013,8806.0,SOUTH,36.0146,-86.6204,"(36.0146, -86.6204)",2010-08,2010,8
284498,20201077484,2010-09-21 08:20:00,2.0,0.0,0.0,N,N,728065,2.0,HEAD-ON,...,TN,37080,3311.0,NORTH,36.3241,-86.8684,"(36.3241, -86.8684)",2010-09,2010,9
284499,20201080059,2010-01-11 17:00:00,3.0,0.0,0.0,N,N,223604,1.0,REAR END,...,TN,37211,8419.0,SOUTH,36.0827,-86.7106,"(36.0827, -86.7106)",2010-01,2010,1
284500,20201081800,2010-10-05 18:12:00,2.0,3.0,0.0,N,N,648796,4.0,ANGLE,...,TN,37220,8613.0,MIDTOW,36.0748,-86.7592,"(36.0748, -86.7592)",2010-10,2010,10
284501,20201342159,2010-04-15 23:40:00,2.0,0.0,0.0,N,Y,525538,4.0,ANGLE,...,TN,37208,4493.0,NORTH,36.1917,-86.8099,"(36.1917, -86.8099)",2010-04,2010,4
284502,20201384997,2010-05-01 14:00:00,1.0,0.0,0.0,N,N,226207,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,TN,37217,8902.0,HERMIT,36.1442,-86.6929,"(36.1442, -86.6929)",2010-05,2010,5
284503,20201416827,2010-05-11 18:40:00,2.0,1.0,0.0,N,N,716889,4.0,ANGLE,...,TN,37206,1113.0,EAST,36.1718,-86.7648,"(36.1718, -86.7648)",2010-05,2010,5
284504,20201550645,2010-06-26 20:28:00,2.0,2.0,0.0,N,N,668414,4.0,ANGLE,...,TN,37203,5625.0,MIDTOW,36.1437,-86.8142,"(36.1437, -86.8142)",2010-06,2010,6
284505,20201784345,2010-09-23 13:15:00,2.0,0.0,0.0,N,N,224538,1.0,REAR END,...,TN,37208,4333.0,NORTH,36.1781,-86.7947,"(36.1781, -86.7947)",2010-09,2010,9
284506,20201840008,2010-10-13 12:44:00,3.0,1.0,0.0,N,N,224640,1.0,REAR END,...,TN,37214,9125.0,HERMIT,36.1677,-86.6633,"(36.1677, -86.6633)",2010-10,2010,10
284507,2020475194,2010-05-31 10:02:00,2.0,1.0,0.0,N,N,224544,2.0,HEAD-ON,...,TN,37076,9535.0,HERMIT,36.2145,-86.6048,"(36.2145, -86.6048)",2010-05,2010,5
284508,2020544731,2010-06-26 15:52:00,2.0,0.0,0.0,N,N,591933,5.0,SIDESWIPE - SAME DIRECTION,...,TN,37207,2133.0,MADISO,36.2693,-86.7557,"(36.2693, -86.7557)",2010-06,2010,6
284509,2020637050,2010-07-29 20:53:00,3.0,0.0,0.0,N,Y,224368,1.0,REAR END,...,TN,37209,5202.0,WEST,36.1538,-86.8423,"(36.1538, -86.8423)",2010-07,2010,7
284510,2020949039,2010-11-24 14:58:00,2.0,0.0,0.0,N,N,472337,1.0,REAR END,...,TN,37217,88942.0,HERMIT,36.1243,-86.6964,"(36.1243, -86.6964)",2010-11,2010,11
284513,20210382905,2010-04-30 17:50:00,2.0,0.0,0.0,N,N,402653,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,TN,37219,4129.0,NaN,36.1637,-86.7790,"(36.1637, -86.779)",2010-04,2010,4
284514,20400639785,2014-07-06 12:45:00,2.0,0.0,0.0,NaN,N,473187,5.0,SIDESWIPE - SAME DIRECTION,...,TN,37115,17040.0,MADISO,0.0000,0.0000,"(0.0, 0.0)",2014-07,2014,7
284515,22010440944,2010-05-19 17:50:00,1.0,1.0,0.0,N,N,608786,2.0,HEAD-ON,...,TN,37207,3007.0,NORTH,36.1986,-86.7801,"(36.1986, -86.7801)",2010-05,2010,5
284516,VU 130097461,2013-08-13 00:00:00,2.0,0.0,0.0,NaN,Y,494,3.0,NaN,...,TN,37204,8525.0,MIDTOW,36.1099,-86.7644,"(36.1099, -86.7644)",2013-08,2013,8

In [35]:
df.to_csv(r'Resources/Metro_Crash_Clean.csv')
df.head()

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Reporting Officer,Collision Type Code,Collision Type Description,...,State,ZIP,RPA,Precinct,Latitude,Longitude,Mapped Location,month_year,Year,Month
12373,20190402257,2019-05-26 12:41:00,2.0,2.0,0.0,NaN,N,769379,4.0,ANGLE,...,TN,37211,8889.0,SOUTH,36.0868,-86.6959,"(36.0868, -86.6959)",2019-05,2019,5
12374,20190397714,2019-05-24 13:15:00,2.0,0.0,0.0,NaN,Y,299238,5.0,SIDESWIPE - SAME DIRECTION,...,TN,37207,19060.0,EAST,36.1922,-86.7755,"(36.1922, -86.7755)",2019-05,2019,5
12376,20160338232,2016-04-13 07:35:00,2.0,0.0,0.0,NaN,N,839052,4.0,ANGLE,...,TN,NaN,NaN,NaN,0.0000,0.0000,"(0.0, 0.0)",2016-04,2016,4
12377,20160838187,2016-09-17 10:20:00,2.0,0.0,0.0,NaN,N,419997,11.0,Front to Rear,...,TN,NaN,NaN,NaN,0.0000,0.0000,"(0.0, 0.0)",2016-09,2016,9
12378,20190413063,2019-05-30 13:23:00,2.0,1.0,0.0,NaN,N,225777,4.0,ANGLE,...,TN,37209,4696.0,WEST,36.1530,-86.8576,"(36.153, -86.8576)",2019-05,2019,5